version: "3.9"
services:
  flask-auth-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-key.json
    volumes:
      - ./firebase-key.json:/app/firebase-key.json
